services:
    web:
        build: .
        command: gunicorn authenticated_things_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
        volumes:
            - .:/code
        ports:
            - "8008:8000"
